### ISSUE TITLE
Auto restart server on file changes (nodemon)

### ISSUE THREAD

**Issue by irfaan008** [Microsoft/vscode-node-debug#113]
It could be better if it restarts server automatically whenever there is a file change. A configuration window can be given to customise the behaviour.

**Comment by matthewoates** [comment]
:+1:

I got debugging working finally (with the IDE running the server), and I got process attaching working (with the IDE attaching to an already running `nodemon --debug server.js` via the instructions [here](https://code.visualstudio.com/Docs/editor/debugging#_node-debugging) but they don't work together.

**Comment by irfaan008** [comment]
@matthewoates Thanks for pointing out this work around. Hope it would be available in built in future release of vs.

**Comment by weinand** [comment]
I do not really understand what this issue is asking for. 
VS Code 1.9.0 (insiders) supports to launch nodemon from a launch config and restarts the debug session automatically when it detected that node.js was restarted. 
See the 1.9.0 release notes:

![2017-01-31_12-22-02](https://cloud.githubusercontent.com/assets/1898161/22462989/f29a2bc2-e7af-11e6-8c68-e31af5738c1f.png)

**Comment by dmk255** [comment]
I don't believe the property `restart` works for `type` python. Is there an equivalent for python configurations?

**Comment by weinand** [comment]
@dmk255 I suggest to ask that on StackOverflow (or in the repository of the python extension as VS Code has no built-in python support).
