### ISSUE TITLE
Expanding an object in the console after a step will show the wrong properties

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-node-debug#114]
- Hit a breakpoint
- Eval something in the console that evaluates to an object
- Step again
- Expand the object in the console
- It will show the properties from another object, or nothing

node-debug2 has the same problem, because we clear variableHandles on each step. I think we need to keep two sets of handles, one for the variables pane that gets cleared on each step, and a second for the console (and logging) that is never cleared. But they would need to map to different spaces somehow, like start on very different numbers. Any other ideas?

**Comment by weinand** [comment]
The v8 debugger protocol spec says this about handle lifetime:

> All objects exposed through the debugger is assigned an ID called a handle. This handle is serialized and can be used to identify objects. A handle has a certain lifetime after which it will no longer refer to the same object. Currently the lifetime of handles match the processing of a debug event. For each debug event handles are recycled.

Since it does not say anything about handles returned from evaluate request being special, I don't think that we can use those handles across stepping (i.e. across stop events).

For this reason the REPL only uses handles returned from the evaluate requests until the next event occurs. At that point the old objects showing in the REPL are frozen and trying to drill deeper into them is prevented and an explanatory message with the 'i' icon is shown. So if an object has never been expanded before a 'step', it will show up as empty after a step (because it was frozen in the empty state).

The issue with that approach is that some behaviour of the underlying debug adapter has leaked into VS Code's generic implementation.

/cc @isidorn

**Comment by weinand** [comment]
@roblourens after discussing this with @isidorn we noticed that VS Code's implementation doesn't freeze the REPL objects after a debug event. That explains why you were seeing properties from another object.

I've created #16504 for this.
