### ISSUE TITLE
Passing environment variables to extensionHost configurations

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode-node-debug#123]
I'd like to set an environment variable in the VS Code process when it gets launched in the debugger so that my extension code can know it's being debugged.  Is there a reason why there's no `env` parameter on the `extensionHost` launch configuration?

Alternatively, is there another way that my extension code can be aware that it's running in the debugger (or loaded using the `extensionDevelopmentPath` parameter)?  I basically just want to change my extension's behavior slightly in this case to use a development path for my language server and debug adapter.

Thanks!

**Comment by weinand** [comment]
@daviwil there is no `env` parameter on the `extensionHost` launch configuration because we are not really launching a new instance of VS Code here but we are communicating to an already running instance of VS Code. So we cannot (easily) pass environment variables as part of a process spawn.

I suggest that in your extension you just search for a '--debug' prefix in the arguments passed to node:
```js
const debug = process.execArgv.filter(v => v.indexOf('--debug') === 0).length > 0;
```

**Comment by daviwil** [comment]
Fantastic idea, thank you!

**Comment by weinand** [comment]
@daviwil I've filed this feature request: https://github.com/Microsoft/vscode/issues/19034

**Comment by daviwil** [comment]
It would be very nice to have an official (and discoverable) way of doing this.  Thanks for filing that!
