### ISSUE TITLE
Link to the Microsoft/vscode-node-debug2?

### ISSUE THREAD

**Issue by jcrben** [Microsoft/vscode-node-debug#142]
It seems that there is a next-generation of this debugger at https://github.com/Microsoft/vscode-node-debug2. Could you link to it so people can find it?

I'm not sure how you want to word it, otherwise I'd open a pull request.

**Comment by weinand** [comment]
The VS Code node debugger automatically switches between node-debug and node-debug2 based on the version of node.js being used because different versions of node support different debug protocols and node-debug and node-debug2 are implementations for those debug protocols.

Both node-debug and node-debug2 are built into VS Code but node-debug2 is basically an implementation detail of node-debug, so end users don't have to deal with node-debug2 directly.

For details see https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_supported-nodelike-runtimes

**Comment by jcrben** [comment]
There's this whole discovery component to open-source projects. Just because something is an implementation detail doesn't mean it shouldn't be easily discoverable. And right now it seems like the repo of node-debug2 is not easily discoverable.

**Comment by weinand** [comment]
if you search for node-debug in VS Code's extension viewlet, you will find both extension easily and they both have links to their repositories.
But I will add node-debug2 to the wiki page you've mentioned.
