### ISSUE TITLE
blackbox/ignore modules for debugging in node

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug#16]
_From @cdaringe on December 2, 2015 0:38_

Hello:

Often when I debug a node.js app, I want to toggle break on "All Exceptions".  In node, that means on **every require statement** it breaks during a `stat` check.

In most of my apps, that's quite a few require statements, and thus quite a few breaks!  The below should look familiar to other nodejs debugging devs!  Even if a _first pass_ as the feature was "Blackbox node internals", that would be a huge help!
<img width="437" alt="screen shot 2015-12-01 at 5 34 10 pm" src="https://cloud.githubusercontent.com/assets/1003261/11518809/cf0e266c-9851-11e5-9db9-d43f2d643063.png">

If you'd like to pass some pointers my way, I'd consider working a PR for the basic ignore?

_Copied from original issue: Microsoft/vscode#892_

**Comment by JAForbes** [comment]
I see this issue is closed?  Does that mean it has been implemented

I find myself never using `All Exceptions` for this exact reason.  

I'd argue it would be better to be able to customize what is blackboxed (a bit like chrome dev tools), so you can still debug `node_modules` that you maintain, and perhaps you'd _like_ to step into `fs` to see how it works for some projects (as an example).

**Comment by weinand** [comment]
@JAForbes No, this issue is open (but the original issue which was filed against the wrong repo has been closed).

**Comment by cdaringe** [comment]
💣 Boom!  nice @weinand, you're the man!

**Comment by Flame2057** [comment]
Well? It's been a year and microsoft hasn't added this? IT'S PRETTY MUCH IMPOSSIBLE TO DEBUG NODE IF YOU HAVE TO STEP THROUGH THE SOURCE OF EVERY SINGLE MODULE YOU USE!!

**Comment by weinand** [comment]
@Flame2057 I don't understand your comment. Please explain.
