### ISSUE TITLE
noDebug flag prevents integrated terminal for getting kill command on restart/stop

### ISSUE THREAD

**Issue by jpike88** [Microsoft/vscode-node-debug#168]
See issue:

https://github.com/Microsoft/vscode/issues/41655

Video of issue:

[http://streaka.testing.videos.s3.amazonaws.com/screencast_2018-01-16_14-07-36.mp4](http://streaka.testing.videos.s3.amazonaws.com/screencast_2018-01-16_14-07-36.mp4)

Basically, it appears the "noDebug" flag is preventing the integrated terminal from being able to receive SIGINT/SIGKILL commands. This is incorrect behaviour as "noDebug" should mean that... I don't want to attach a debugger. It DOESN'T mean I want to lose control of starting/stopping the process.

I have enabled the "noDebug" flag as a workaround to this issue:

https://github.com/Microsoft/vscode-node-debug/issues/165

However this prevents me from using the integratedTerminal because no link is established at all. Doesn't make sense... just because I don't want to attach a debugger, that doesn't mean I want the restart/stop commands to be disabled altogether.

**Comment by weinand** [comment]
Using "noDebug" means that the debuggee is started with debugging disabled, so no debugger attaches to the debuggee.

When combining this with an integrated terminal, it has the consequence that VS Code can no longer kill the debuggee on "Stop". 

The reason is:
If the debuggee started in an integrated terminal, VS Code does not know its process ID because it was launched via some intermediate shell process. Without knowing the process ID VS Code cannot kill it.

In debug mode, this is not a problem because VS Code is attached to the process and can get its process ID via some "evaluate" call.

In noDebug mode, VS Code is not attached and cannot use the "evaluate" trick.
