### ISSUE TITLE
Remote debugging of node.js in a docker container

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode-node-debug#29]
_From @djabraham on December 19, 2015 1:37_

First, I want to thank Microsoft for VSCode. It's truly wonderful to use both this powerful editor and TypeScript together, with everything else the open-source community has to offer.

I have issues with debugging when node.js MUST run in a docker container, in order to connect to other containers and so forth. I know that remote debugging isn't supported yet, but it may actually be easy to fix a couple of obstacles that I encountered, since I was able to find work arounds myself. The major issues with debugging node.js in a locally hosted docker container that I saw were as follows:

1) VSCode obtains and then monitors the node process PID, then shuts down the debugger after several seconds if it notices that the PID isn't actually running. This is not idea, when the process is running in a separate container, so it would be nice if that requirement were optional.

2) VSCode uses absolute paths to the source code. This is not ideal if the source code's location on the host is different than that of the docker container. Containers use different mappings all the time, so relative path would be a much better approach.

I was able to work around the first issue by creating a small proxy that is run on the host, along side VSCode. All the proxy does if forward packets back and fort between two ports, for the most part. But when it sees the PID packet being returned from node.js, it substitutes its own PID. This is in order to prevent VSCode from exiting prematurely. The source for the proxy is here, by the way:

https://gist.github.com/djabraham/19af4ea435dd94418af0

I was able to work around the second issue by bind-mounting the source code into the same path on the host as within the docker container. This could be a major pain for users on OSX, because it required downloading and compiling bind, along with other utilities, and performing the mount. And while it works on a MAC; however, I am not sure how to do something similar on Windows.

Thanks again for all the great tooling!

_Copied from original issue: Microsoft/vscode-debugadapter-node#2_

**Comment by weinand** [comment]
@djabraham this is great feedback, thanks a lot. I will move the issue over to the vscode-node-debug repo because both issues are specific to node-debug and the fixes will happen in that repository.

This repo "vscode-debugadapter-node" contains only the protocol and some default adapter code.

**Comment by silverbp** [comment]
This is awesome! Thanks for figuring this out! This should get debugging working for me!

I assume the bind part is not needed if you can just volume map it in to the same path has what you have it on your host? In our case that's possible!

**Comment by m90** [comment]
I am still experiencing the same behavior when using the proxy script. It will attach itself for something like 3 seconds and then exit. What could be causing this?

**Comment by djabraham** [comment]
if you are using 5858 in container, then you should be using 5859 in VSCode.

    $ node debug-proxy 5859 5858

    Local Port:        5859
    Remote Port:       5858

    debugger-proxy: localEditorSocket listening for connection (127.0.0.1:5859)

**Comment by m90** [comment]
@djabraham Great! Now it works for me too, Thanks a lot for that.

I am getting a parsing error from time to time though:

```
debugger-proxy: fatal error, shutdown initiated
SyntaxError: Unexpected token C
    at Object.parse (native)
    at Socket.<anonymous> (/home/m90/project/.vscode/debugproxy.js:106:38)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
debugger-proxy: executed localServer shutdown
debugger-proxy: executed remoteProcessDetach
```

**Comment by silverbp** [comment]
It works for me, but I'm using osx and modified the script to connect to the virtual box vm running docker so I end up doing `node debug-proxy 5858 5858`. The destination port is scripted to go to `docker-machine ip dev`

It might make things a little more clear if you state the OS you're trying to do this on. The script actually solves the problem of vscode not supporting remote debugging as well since the proxy connects to the remote docker and then exposes the 5858 locally.

**Comment by djabraham** [comment]
Those are good points, I am running docker on 127.0.0.1, so I didn't even think of adding support for a host name. 

I did see those fatal parsing errors a few times, but I haven't got enough of them to determine why. Node emits a response on connect that looks different than the norm, and I think I saw it combined with a JSON response once, like so..

    Content-Length: 164

    {"seq":91,"request_seq":1,"type":"response","command":"evaluate","success":true,"body":{"handle":0,"type":"number","value":22,"text":"22"},"refs":[],"running":true}

    Type: connect
    V8-Version: 4.6.85.31
    Protocol-Version: 1
    Embedding-Host: node v5.1.0
    Content-Length: 0

So maybe it's caused by some response packets getting merged somehow? 

I created this under the assumption that it was only needed temporarily, because they are actively working on VSCode. But please let me know if you find any improvements in the meantime.

**Comment by m90** [comment]
Did anyone of you look into how to make this portable yet? I'd really like to enable my team to use this as well, yet it relies on quite some magic still.

Open questions are:

- What's the best way to automate the path mapping? While setting it in the `docker-compose.yml` works fine, every developer will have different values here.
- What's the best way to automate startup of the proxy script?

**Comment by weinand** [comment]
@m90 the corresponding feature request is Microsoft/vscode#1591

**Comment by silverbp** [comment]
we have templated our docker-compose files with variables that get injected, one of them is working directory. So we have a build system that wraps the docker stuff and actually caches npm modules etc. We run everything in a docker container. It works out really well, although we still have some friction points here and there. I'm not going to put a lot of time in the automated startup of the proxy script since I assume vscode will fix this at some point.

here is an example

``` yml
## # build-template
${safename}:
  image: ${buildimage}
  ports:
    - '5858:5858'
    - '5859'
    - '3000:3000'
  working_dir: ${workingdir}
  volumes:
    - './scripts/:/bootstrap.d/'
    - '/Users:/Users'
  links:
    - database
database:
  image: postgres:9.4
  ports:
    - '5432:5432'
```

now keep in mind this is on OS X and /Users is the only thing mapped into virtual box by default which gets mapped into the boot2docker VM. This gets a little easier if you're running a linux distro, but by doing the entire /Users folder, we can also utilize `npm link` with other libraries from within the container itself. The ${workingdir} gets filled in with the appropriate dir when we run `build` and everyone has OS X, otherwise you could also specifically map in the working directory to the working directory. (But then you don't get the npm linking stuff either).

**Comment by silverbp** [comment]
Also they have this feature set for the January milestone which would make most of the above unnecessary if they handle the path issue and the remote debugging issue.

**Comment by weinand** [comment]
A quick update for the upcoming January drop:
* A remote debug session will no longer terminate after 3 seconds (a watchdog timer was tracking the **local** existence of the node process which does not really make sense in the remote case...)
* the `attach` launch config got the `address` attribute back. So it is again possible to specify a TCP/IP address. Please note that remote debugging is only supported on recent version of node.
* the `attach` launch config now supports a `localRoot` and a `remoteRoot` attribute that can be used to map paths between a local VS Code project and a (remote) node folder. This works even across different operating systems.

**Comment by djabraham** [comment]
I could swear I said thanks for this already. Oh well, thanks again for this awesome capability! 

VSCode is the only thing I can see at this point that supports remote debugging with minimal intrusion. All I have to do now is add a couple cli parameters to node (--debug-brk  --nolazy).

**Comment by styfle** [comment]
I am trying to debug a docker container and I am unable to connect.
Is there official documentation for remote debugging anywhere?

**Comment by weinand** [comment]
@styfle please see https://code.visualstudio.com/docs/editor/debugging and search for section "Remote Debugging Node.js"

**Comment by djabraham** [comment]
If you cannot connect at all, then the problem may lie with Docker setup. Make sure you expose port 5858 within the container. You will also have to setup NAT forwarding for any ports you've exposed, within VirtualBox.

Set up a permanent VirtualBox NAT Port forwarding, under OSX:
```
$ VBoxManage modifyvm "default" --natpf1 "node-debug,tcp,,5858,,5858";
```
If the `default` boot2docker vm (docker-machine) is already running, you can run this command:
```
$ VBoxManage controlvm "default" natpf1 "node-debug,tcp,,5858,,5858";
```
Launch Docker with open ports as needed, using ```/bin/sh``` (alpine) or ```/bin/bash``` (node):
```
$ docker run -it -p 8080:8080 -p 5858:5858 --name mycontainer -v $(PWD):/src/app /bin/sh

> node --debug-brk server.js
```

**.vscode/launch.config**
```
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Attach to Docker",
			"type": "node",
			"request": "attach",
			"port": 5858,
			"address": "localhost",
			"localRoot": "${workspaceRoot}",   // Path within host (i.e. "/Users/../server"),
			"remoteRoot": "/src/app"           // Path withing Docker container
		}
	]
}
```

**Dockerfile**
```
FROM gliderlabs/alpine

WORKDIR /src/app
ADD . /src/app

RUN npm install

EXPOSE 8080
EXPOSE 5858   # not for production

CMD ["node", "server.js"]   # does not include --debug-brk, by default
```

**Comment by stefanwalther** [comment]
I have added a step-by-step walkthrough here: https://github.com/stefanwalther/boilerplate-typescript-rest-docker
