### ISSUE TITLE
Strange breakpoint behaviour

### ISSUE THREAD

**Issue by edvinv** [Microsoft/vscode-node-debug#38]
Type script code:
```typescript
import * as request from "request";

let options = {
	url: "https://upload.wikimedia.org/wikipedia/commons/3/3d/LARGE_elevation.jpg",
	method: "GET",
	encoding: null
};

request(options, (err, response, body) => {
	console.log("done");
});

console.log("downloading...");
```

Program works ok from console. Now set breakpoints on request(...) and on console.log("done"); line. Debugger will stop correctly on request line but when you press F5, you will only get 'Paused on breakpoint.' in call stack and no other clue where debugger has stopped. If you press  F5 again you get error 'request 'continue': request 'continue' was cancelled because node is unresponsive'.

**Comment by winsome** [comment]
I've also been seeing `request 'continue': request 'continue' was cancelled because node is unresponsive` every time I set a breakpoint in a callback and try to continue or step through it.

A related error message that I've seen is `request 'continue': node did not respond to request 'continue' in a reasonable amount of time`

**Comment by weinand** [comment]
This is another instance of https://github.com/Microsoft/vscode-node-debug/issues/11
If the breakpoint is hit, the `body`argument is a 100k Buffer object which is automatically included as a huge JSON object in top stack frame. This makes the stackframe request timeout and the VSCode UI behave badly. This is a known problem of the node V8 debugger protocol. For node 0.12.x VSCode was able to workaround the issue by injecting alternative debug protocol requests into the debug target which scale better. This code injects stopped working in node >= 3.x versions.

**Comment by edvinv** [comment]
@weinand thanks, good to know...

and yes, I also noted that problem was only when downloading large files..

**Comment by heqian** [comment]
Just had the similar issue when I was debugging a Node.js script that takes about 6 seconds while launching (loading and preprocessing a large .csv file).

Tried to change the `NodeV8Protocol.TIMEOUT` value in `nodeV8Protocol.js` and the `NodeDebugSession.NODE_TERMINATION_POLL_INTERVAL` value in `nodeDebug.js`. Didn't make any difference though.

**Comment by weinand** [comment]
@heqian 'similar issue' == large data structures? Changing the timeouts does only make sense if we understand what the issue is. If you provide details I can investigate.

**Comment by heqian** [comment]
@weinand Yes, large date structure (a list with 525,377 items).
To rule out the possibility that it may be caused by timeout, I removed this large date structure (the list) and added a huge loop before the breakpoint.
```js
var i = 0;
while (i < 3000000000) {
	i++;
}
```
This loop took about 23 seconds, and then the script stopped at the breakpoint correctly.

**Comment by weinand** [comment]
@heqian the node V8 debugging protocol (which we do not control) has no good support for large data structures: the whole data structure is sent over the wire which slows things down. So 525,377 items is way too much and even node-inspector will choke on this. VS Code tries to work around that issue but this only works in node <= v0.12.9. Try to use that version and it should work.

**Comment by heqian** [comment]
@weinand Thanks! I saw your previous comment. I saw some discussions between the MS and Node.js communities on ChakraCore (https://blogs.windows.com/msedgedev/2016/01/19/nodejs-chakracore-mainline/). I'm not sure if ChakraCore has this issue. Is there any chance you guys will collaborate with Node.js team in the future to work out a solution?

**Comment by weinand** [comment]
@heqian yes, we are working on this. But first let's get ChakraCore run on all platforms.

**Comment by heqian** [comment]
@weinand Looking forward to it :)

**Comment by cherchyk** [comment]
Having same issue.  Data structures are big.

**Comment by msklvsk** [comment]
Same issue, 5MB of binary data.

**Comment by felimartina** [comment]
Same issue here! any leads?

**Comment by frogcjn** [comment]
How can I avoid this? It makes me crazy.

**Comment by deyoppe** [comment]
Having the same problem.
If I attempt to debug a file with a large json, debug becomes unusable and forces me to terminate the process.

This is the minimum reproduction case I found, with data.json being a 200mb file nested several levels deep.
```
console.log("A");
var foo = require('data.json');
console.log("B");
```
Here, if I breakpoint on the first line everything goes fine. I can continue no problem. Same on the second line. However, once I hit the third line, I can't continue anymore, probably because foo now contains 200mb worth of data.

**Comment by weinand** [comment]
@deyoppe if you are able to use VS Code 1.6.1 and node >= 6.3 please try to use our new node-debug by changing 'node' to 'node2' in your launch config.
Does this make a difference?

**Comment by deyoppe** [comment]
I can confirm that with this solution everything works flawlessly.

Note: I had to upgrade node 6.3.1 to 6.8.1, otherwise I'd run into [this issue](https://github.com/Microsoft/vscode-node-debug2/issues/27).

Thanks!

**Comment by weinand** [comment]
@deyoppe great, thanks for trying.

**Comment by paololabe** [comment]
I had problem od timeout and "node.js not responding" inspecting object after the breakpoint was fired, I solved switching to node2 in lunch.json with node 6.9.x.

**Comment by DarrenCook** [comment]
This one is driving me crazy too; debugging an Electron app, most of the time I get this. Having read this thread, I now see the common factor was having a large data structure in the variables.

I tried "node2" but now the debugger won't even start:
"Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:47101)."

(That might be due to one of the hacks I have to get Electron debugging to work at all; I'll have to come back and try this when more time to experiment. For the moment, breakpoints off, excessive logging on !)

**Comment by weinand** [comment]
@DarrenCook You cannot debug with `"protocol": "inspector"` (aka node2) since the node.js built into Electron does not yet support the "inspect" protocol. It only supports the "legacy" protocol which has known performance issues with large data structures.
