### ISSUE TITLE
not stopping on debug breakpoints using node lite-server launch/attach configuration

### ISSUE THREAD

**Issue by myusrn** [Microsoft/vscode-node-debug#55]
I'm trying to use vscode node debug/launch settings on a simple web app ng2 application, based on https://angular.io/docs/ts/latest/quickstart.html, where the web server that is launched for debugging is the https://www.npmjs.com/package/lite-server, that builds on top of https://www.browsersync.io/ package. 

I can get vscode to successfully launch the node package provided web server but it is not stopping on any of my typescript soft breakpoints.   

This can be repro’d by cloning https://github.com/myusrn/vscng2qs | executing "npm install" to restore modules | opening in vscode | building typescript using ctrl+shift+b [ or "npm run tsc" | setting a few break points in app/main.ts and/or app.component.ts | then selecting vscode debug "Launch lite-server" option.

**Comment by weinand** [comment]
@myusrn I've tried to reproduce this on Windows but I think something in your project configuration is broken.

Whenever I try to repro issues like this, I assume that the generated source maps are broken. (In your setup this was clearly the case because you are setting the `sourceRoot` to some absolute path on your disk, which doesn't work for me. I suggest to always try to use relative path when setting `sourceRoot`). 

The first thing I do is to disable source maps and I insert a `debugger` statement into the generated JavaScript file where the breakpoint is not hit (first line in `app.component.js`). And I enable `stopOnEntry`. 

Then I ran the "Launch lite-server" config. The debugger hit the entry point in `lite-server` but it did not stop on the debugger statements. This is an indication that either your code `app.component.js` is not loaded at all or that a second node instance is launched but not configured for debug mode. Since I couldn't find another node in TaskManager I assume that `app.component.js` is just not loaded.

**Comment by myusrn** [comment]
hi @weinand thanks for the response.   

since with this setup i'm just using the npm lite-server package/app to host the html/css/js files, in lieu of .net execution environment [dnx] hosted web host "dnx web", then it would seem its not really a node app debugging scenario but rather a browser one only.

so i'm closing issue given vscode chrome browser debugging extension does work as expected in this case and will leave use of vscode node app debugging extension for when that is the actual target.
