### ISSUE TITLE
Breakpoints unreliable with .ts files

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode-node-debug#58]
_From @notenoughneon on March 28, 2016 18:19_

- VSCode Version: 0.10.11
- OS Version: OS X 10.10.5
- Typescript: 1.8.9
- Node: 5.9.0

Possibly related to #2157, #1384

After upgrading typescript from 1.6 to 1.8.9, and node from 0.12 to 5.9.0, I noticed breakpoints no longer working and other strange behavior.
* Debugger fails to stop at breakpoints in .ts file
* Debugger shows .js file instead of .ts when attaching to node --debug-brk
* Double entries for same breakpoint appear in "breakpoints" pane

Its been difficult to produce a good test case for this bug due to nondeterministic behavior. I've seen symptoms appear or disappear after:
* Commenting/uncommenting parts of the code and recompiling
* Copying the .ts file to an identical copy and debugging

Possible causes that have been ruled out:
* "outDir" setting (separate outDir or not makes no difference)
* "typescript.tsdk" 1.8.9 mismatch (tried setting to installed version of typescript vs bundled 1.8.2)
* Code with promises or callbacks (issue was produced in case with only console.log())
* Breakpoint being on first line (breakpoints throughout entire code may fail)

Steps to Reproduce:

test.ts:
```typescript
import fs = require('fs');
var cb1 = function(err, stats) {
    console.log('break here 1');
};
fs.stat('.', cb1);

var cb2 = function() {
    console.log('break here 2');
}
setTimeout(cb2, 1000);
```

tsconfig.json:
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "sourceMap": true
    }
}
```

launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach",
            "request": "attach",
            "type": "node",
            "port": 5858,
            "sourceMaps": true
        }
    ]
}
```

1. tsc
2. node --debug-brk test.js
3. Set breakpoints in ts file and attach to process
4. Commenting/uncommenting the top or bottom section and retrying causes the breakpoint issue to manifest eventually

_Copied from original issue: Microsoft/vscode#4718_

**Comment by weinand** [comment]
@notenoughneon if you use the 'Attach' mode of VS Code make sure, that you pass the '--nolazy' to option to node. Without this, node will parse JavaScript lazily which does not work well with breakpoints and source maps.

If there is no pressing need to use 'Attach' I suggest to use 'Launch' because there you can add '--nolazy' to your launch config.

Only if your generated JavaScript lives side by side with the source no 'outDir' attribute is necessary. Whenever the generated JavaScript lives in a different folder, you have to specify that folder as the 'outDir' attribute.

Please reopen if the problem still exists after following my suggestions.
