### ISSUE TITLE
Breakpoints not working in .ts files

### ISSUE THREAD

**Issue by notenoughneon** [Microsoft/vscode-node-debug#59]
VSCode Version: 0.10.11
OS Version: OS X 10.10.5
Typescript: 1.8.9
Node: 5.9.0

Continuation of #58.

Opening a new folder with the files below, I can consistently reproduce the case where a breakpoint set in util.ts never hits. As a workaround, enabling stopOnEntry and then stepping through until entering util.js will cause breakpoints in util.ts to begin working. Copying everything to a new project folder will revert it to the broken breakpoint state.

I discovered this while trying to figure out why breakpoints in mocha tests never worked, but some simple single-file programs occasionally did. It seems you need to manually step through each js file for breakpoints in the corresponding ts file to begin working.

main.ts:
```typescript
var util = require('./util');

console.log(util.square(5));
```

util.ts:
```typescript
export function square(n) {
    return n * n;
}
```

tsconfig.json:
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        "sourceMap": true
    }
}
```

.vscode/launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "request": "launch",
            "type": "node",
            "stopOnEntry": true,
            "program": "${workspaceRoot}/main.js",
            "cwd": "${workspaceRoot}",
            "runtimeArgs": ["--nolazy"],
            "sourceMaps": true
        }
    ]
}
```

**Comment by weinand** [comment]
@notenoughneon Sorry for the late reply but I did not expect new issues in this repository, because I got 99% of all node-debug issues in the main VS Code repository.

I just tried your sample with VS Code 1.2 and I cannot see the issue that the breakpoint is not hit in util.ts:2 (and this is even if "stopOnEntry" is set to false).

So what you've seen in VS Code 0.10.11 was probably a bug that has been fixed in the meantime.

One comment (and explanation) about breakpoints in short running node.js programs (e.g. mocha tests):

If you want to debug a short running node program, it is very important to use the `--debug-brk` option because it will stop the execution of the program until the debugger (e.g. VS Code) has connected. Because the execution is stopped, the debugger has enough time to set all breakpoints. This makes it possible that even breakpoints in the early startup phase of the program are hit.

If you only use `--debug` when launching node, the execution of the program is **not** stopped and the program might have already run through its startup code before the debugger had a chance to connect and register the breakpoints (or if the program is very short running it might even have been terminated before the debugger could connect).

For this reason VS Code always launches node programs with the `--debug-brk` option as you can see in the debug console:

![2016-06-09_15-33-48](https://cloud.githubusercontent.com/assets/1898161/15931358/c234c742-2e57-11e6-9fbf-7a0f083bed5e.png)
 
The `stopOnEntry` attribute of the launch configuration only controls whether the initial stop is shown to the user or not. It should not have an influence on whether breakpoints in the startup phase of a program are hit or not.

**Comment by notenoughneon** [comment]
@weinand It's working for me now in VS Code 1.2. Thanks for the explanation on how stopOnEntry works!

**Comment by weinand** [comment]
@notenoughneon great to hear that this works for you.
