### ISSUE TITLE
Source map support is very flakey and broken

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode-node-debug#68]
In my src directory I am running this.

node --debug ../../built/local/tsc.js

My attach config is as follows

```
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "sourceMaps": true
        }
```

Source maps worked once and then they stopped working. It always complains it cannot find source maps.

Expected:
Its smart enough to figure out where the actual source file is and bind the breakpoint, if it can't then it should give a very useful error. Currently I have been at it for almost half a day.

Actual:
Source map support for debugging is very frustrating and broken experience.

**Comment by weinand** [comment]
@nojvek if the generated files are not side-by-side with the source, you have to specify the root folder of the generated code in your attach config in the `outDir` attribute

E.g. if your folder with the generated code is `built` and it is located in the project directory use this: 
```
        {
            "name": "Attach",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/built"
        }
```

**Comment by weinand** [comment]
@nojvek does it help if you set `outDir`?

**Comment by nojvek** [comment]
I did try that but it seems the once the adapter connects to node, it crashes.
 Would be really nice to have a verbose logging option, so we can see what the adapter is trying to do. Right now its seems like a blackbox. When it works it works, when it doesn't, there is little feedback on what needs to be fixed.

**Comment by weinand** [comment]
@nojvek here are some tipps:
- you can enable tracing by adding a `"trace": "all"` to your launch config. If you specify `"sm"` instead of `"all"` you will only see source map related information.
- If you launch 'node.js' yourself (outside of VS Code) please don't forget the `--nolazy` option.
- running node.js inside 'src' and then reaching over to 'built' seems overly complex to me as node.js has nothing to do with the source, so there is no need to run node there. I suggest to run node in the common parent folder of `src` and `built`. 
- 99% of all problems with source maps are related to incorrect paths inside the source map. Depending on how you generate source maps the paths are either relative or absolute. But it any case they must match to the layout of your project. Please verify for a single file that the paths inside the generated JavaScript and the source map make sense. The path at the end of the generated file should point to the source map, and the concatenated `sourceRoot` and `sources` paths in the source map should point to the source.

**Comment by nojvek** [comment]
We should add trace to the package.json so it comes up in auto complete. 

I think as a nicer experience, when source maps are enabled and certain sources cannot be mapped. It should give info errors that the sources cannot be found and what paths its expecting to find sources.

**Comment by weinand** [comment]
Closing because we are not planning to implement this within the next 12 months.

**Comment by nojvek** [comment]
I didn't realize this was still open. I have made some PR's in vscode-chrome-debugger that got merged a while ago. They give much more detailed errors related to sourcemaps.
